<?php
/**
 * Created by PhpStorm.
 * User: OTZ_VAV
 * Date: 15.01.2019
 * Time: 11:21
 */

namespace app\widgets;

use app\models\Category;
use yii\base\Widget;

class MenuWidget extends Widget
{
    public $data;

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        $this->data = new Category();
        $this->data = $this->data->getCategories();//Получаем всю информацию из таблицы category
        $this->data = $this->categoryToTemplate($this->data);
        return $this->data;

    }

    public function categoryToTemplate($data) {
        ob_start();
        include __DIR__ .'/template/menu.php';
        return ob_get_clean();
    }

}