<?php
/**
 * Created by PhpStorm.
 * User: OTZ_VAV
 * Date: 15.01.2019
 * Time: 9:56
 */

namespace app\models;
use yii\db\ActiveRecord;
use Yii;

class Good extends ActiveRecord
{
    public static function tableName()
    {
//        return parent::tableName(); // TODO: Change the autogenerated stub
        return 'good';
    }

    public function getAllGoods() {
        $goods = Yii::$app->cache->get('goods');//Запрос на данные из кэша. Если нет, то обращаемся к БД.
        if (!$goods) {
            $goods = Good::find()->asArray()->all();//Найди все товары в таблице Good
            Yii::$app->cache->set('goods', $goods, 10);//Записать данные в кэш
        }

        return $goods;
    }

    public function getGoodsCategories($id) {
//        $catGoods = Good::find()->where(['category' => $id])->asArray()->all();
//        return $catGoods;

        $catGoods = Yii::$app->cache->get('catGoods');
        if (!$catGoods) {
            $catGoods = Good::find()->where(['category' => $id])->asArray()->all();
            Yii::$app->cache->set('catGoods', $catGoods, 10);
        }
        return $catGoods;
    }

    public function getSearchResults($search) {
        $searchResults = Good::find()->where(['like', 'name', $search])->asArray()->all();
        return $searchResults;
    }

}